const ValueTypes = [
  'script',
  'void',
  'passthrough',
  'boolean',
  'real',
  'short',
  'long',
  'string',
  'trigger_volume',
  'cutscene_flag',
  'cutscene_camera_point',
  'cutscene_title',
  'cutscene_recording',
  'device_group',
  'ai',
  'ai_command_list',
  'starting_profile',
  'conversation',
  'navpoint',
  'hud_message',
  'object_list',
  'sound',
  'effect',
  'damage',
  'looping_sound',
  'animation_graph',
  'actor_variant',
  'damage_effect',
  'object_definition',
  'game_difficulty',
  'team',
  'ai_default_state',
  'actor_type',
  'hud_corner',
  'object',
  'unit',
  'vehicle',
  'weapon',
  'device',
  'scenery',
  'object_name',
  'unit_name',
  'vehicle_name',
  'weapon_name',
  'device_name',
  'scenery_name',
  'point_reference',
  'network_event',
  'string_id',
  'model_state',
  'shader',
  'bitmap',
  'unit_seat_mapping',
  'ai_orders',
  'ai_command_script',
  'ai_behavior',
  'style',
  'structure_bsp',
  'render model',
  'folder',
  'any tag',
  'ai_line',
  'mp_team',
  'cinematic scene definition',
  'zone_set',
  'cinematic definition',
  'cinematic_lightprobe',
  'controller',
  'button preset',
  'joystick preset',
  'player color',
  'player character type',
  'voice output setting',
  'voice mask',
  'subtitle setting',
  'event',
  'bink definition',
  'designer_zone',
  'any tag not resolving',
  'animation budget reference',
  'looping sound budget reference',
  'sound budget reference'
] as const;

export default ValueTypes;